### ISSUE TITLE
Migrate to Python 3.12+, update peewee, update pyzmq

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/skale-admin#1172]
Currently, we're using `python:3.11-bookworm` as a base for our `skale-admin` docker container. 

`utcfromtimestamp` is deprecated in 3.11 and the new function is incorrectly handled by peewee in 3.11:

```python
def test_timestamps(skaled_am):

    tm = time.time()
    
    new_dt1 = datetime.datetime.fromtimestamp(tm, tz=datetime.timezone.utc)
    skaled_am.schain_record.set_repair_date(new_dt1)
    repair_date1 = skaled_am.schain_record.repair_date

    new_dt2 = datetime.datetime.fromtimestamp(tm)
    skaled_am.schain_record.set_repair_date(new_dt2)
    repair_date2 = skaled_am.schain_record.repair_date

    new_dt3 = datetime.datetime.utcfromtimestamp(tm)
    skaled_am.schain_record.set_repair_date(new_dt3)
    repair_date3 = skaled_am.schain_record.repair_date

    print('1 ----------')
    print(repair_date1)
    print(repair_date2)
    print(repair_date3)
    
    print('1.1 ----------')
    print(type(new_dt1))
    print(type(new_dt2))
    print(type(new_dt3))
    
    print('2 ----------')
    print(new_dt1.timestamp())
    print(new_dt2.timestamp())
    print(new_dt3.timestamp())

    print('3 ----------')  
    print(repair_date1)
    print(repair_date2)
    print(repair_date3)
    print('----------')
    
    print('3.1 ----------')
    print(type(repair_date1))
    print(type(repair_date2))
    print(type(repair_date3))
    
    print('4 ----------')  
    print(repair_date1.timestamp())
    print(repair_date2.timestamp())
    print(repair_date3.timestamp())
    print('----------')
```

Results in:

```
1 ----------
2025-04-16 12:35:01.045218+00:00
2025-04-16 13:35:01.045218
2025-04-16 12:35:01.045218
1.1 ----------
<class 'datetime.datetime'>
<class 'datetime.datetime'>
<class 'datetime.datetime'>
2 ----------
1744806901.045218
1744806901.045218
1744803301.045218
3 ----------
2025-04-16 12:35:01.045218+00:00
2025-04-16 13:35:01.045218
2025-04-16 12:35:01.045218
----------
3.1 ----------
<class 'str'>
<class 'datetime.datetime'>
<class 'datetime.datetime'>
4 ----------

FAILED tests/schains/monitor/action/skaled_action_test.py::test_timestamps - AttributeError: 'str' object has no attribute 'timestamp'
```

Fix available in the latest `peewee` but it requires python 3.12+
We need to update `peewee` to the latest version.

Our current version of `pyzmq` doesn't work with python3.12 and should be upgraded first.

**Comment by dmytrotkk** [comment]
https://github.com/zeromq/pyzmq/issues/2030

**Comment by dmytrotkk** [comment]
https://github.com/coleifer/peewee/issues/2700
